In [35]:
import pandas as pd
from sqlalchemy import create_engine

In [36]:
premise_file = "data_min_vers.csv"
data_min_df = pd.read_csv(premise_file)
data_min_df.head()

,flight_number,mission_name,upcoming,launch_year,launch_date_unix,launch_date_utc,launch_date_local,rocket/rocket_id,rocket/rocket_name,rocket/rocket_type,...,rocket/first_stage/cores/1/landing_vehicle,rocket/first_stage/cores/2/core_serial,rocket/first_stage/cores/2/flight,rocket/first_stage/cores/2/block,rocket/first_stage/cores/2/reused,rocket/first_stage/cores/2/land_success,rocket/first_stage/cores/2/landing_type,rocket/first_stage/cores/2/landing_vehicle,rocket/second_stage/payloads/1/norad_id/1,rocket/second_stage/payloads/1/customers/1
0,1,FalconSat,False,2006,1143239400,2006-03-24T22:30:00.000Z,2006-03-25T10:30:00+12:00,falcon1,Falcon 1,Merlin A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,DemoSat,False,2007,1174439400,2007-03-21T01:10:00.000Z,2007-03-21T13:10:00+12:00,falcon1,Falcon 1,Merlin A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Trailblazer,False,2008,1217648040,2008-08-02T03:34:00.000Z,2008-08-02T15:34:00+12:00,falcon1,Falcon 1,Merlin C,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,RatSat,False,2008,1222643700,2008-09-28T23:15:00.000Z,2008-09-28T11:15:00+12:00,falcon1,Falcon 1,Merlin C,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,RazakSat,False,2009,1247456100,2009-07-13T03:35:00.000Z,2009-07-13T15:35:00+12:00,falcon1,Falcon 1,Merlin C,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [37]:
data_cols = ["flight_number", "launch_date_utc", "launch_site/site_name", "rocket/first_stage/cores/0/core_serial", "rocket/second_stage/payloads/0/payload_id",
            "rocket/second_stage/payloads/1/payload_mass_kg", "rocket/second_stage/payloads/1/orbit",
             "rocket/second_stage/payloads/0/customers/0", "launch_success", "rocket/first_stage/cores/0/land_success"]
data_min_df_transformed= data_min_df[data_cols].copy()
data_min_df_transformed

,flight_number,launch_date_utc,launch_site/site_name,rocket/first_stage/cores/0/core_serial,rocket/second_stage/payloads/0/payload_id,rocket/second_stage/payloads/1/payload_mass_kg,rocket/second_stage/payloads/1/orbit,rocket/second_stage/payloads/0/customers/0,launch_success,rocket/first_stage/cores/0/land_success
0,1,2006-03-24T22:30:00.000Z,Kwajalein Atoll,Merlin1A,FalconSAT-2,NaN,NaN,DARPA,False,False
1,2,2007-03-21T01:10:00.000Z,Kwajalein Atoll,Merlin2A,DemoSAT,NaN,NaN,DARPA,False,False
2,3,2008-08-02T03:34:00.000Z,Kwajalein Atoll,Merlin1C,Trailblazer,NaN,LEO,NASA,False,False
3,4,2008-09-28T23:15:00.000Z,Kwajalein Atoll,Merlin2C,RatSat,NaN,NaN,SpaceX,True,False
4,5,2009-07-13T03:35:00.000Z,Kwajalein Atoll,Merlin3C,RazakSAT,NaN,NaN,ATSB,True,False
5,6,2010-06-04T18:45:00.000Z,CCAFS SLC 40,B0003,Dragon Qualification Unit,NaN,NaN,SpaceX,True,False
6,7,2010-12-08T15:43:00.000Z,CCAFS SLC 40,B0004,COTS Demo Flight 1,NaN,LEO,NASA(COTS),True,False
7,8,2012-05-22T07:44:00.000Z,CCAFS SLC 40,B0005,COTS Demo Flight 2,NaN,NaN,NASA(COTS),True,NaN
8,9,2012-10-08T00:35:00.000Z,CCAFS SLC 40,B0006,SpaceX CRS-1,400.0,LEO,NASA (CRS),True,NaN
9,10,2013-03-01T19:10:00.000Z,CCAFS SLC 40,B0007,SpaceX CRS-2,NaN,NaN,NASA (CRS),True,NaN
10,11,2013-09-29T16:00:00.000Z,VAFB SLC 4E,B1003,CASSIOPE,NaN,NaN,MDA,True,False
11,12,2013-12-03T22:41:00.000Z,CCAFS SLC 40,B1004,SES-8,NaN,NaN,SES,True,NaN
12,13,2014-01-06T18:06:00.000Z,CCAFS SLC 40,B1005,Thaicom 6,NaN,NaN,Thaicom,True,NaN
13,14,2014-04-18T19:25:00.000Z,CCAFS SLC 40,B1006,SpaceX CRS-3,NaN,NaN,NASA (CRS),True,True
14,15,2014-07-14T15:15:00.000Z,CCAFS SLC 40,B1007,Orbcomm-OG2-M1,NaN,NaN,Orbcomm,True,True
15,16,2014-08-05T08:00:00.000Z,CCAFS SLC 40,B1008,AsiaSat 8,NaN,NaN,AsiaSat,True,NaN
16,17,2014-09-07T05:00:00.000Z,CCAFS SLC 40,B1011,AsiaSat 6,NaN,NaN,AsiaSat,True,NaN
17,18,2014-09-21T05:52:00.000Z,CCAFS SLC 40,B1010,SpaceX CRS-4,NaN,NaN,NASA (CRS),True,False
18,19,2015-01-10T09:47:00.000Z,CCAFS SLC 40,B1012,SpaceX CRS-5,NaN,NaN,NASA (CRS),True,False
19,20,2015-02-11T23:03:00.000Z,CCAFS SLC 40,B1013,DSCOVR,NaN,NaN,NASA,True,True
20,21,2015-03-02T03:50:00.000Z,CCAFS SLC 40,B1014,ABS-3A,2205.0,GTO,ABS,True,NaN
21,22,2015-04-14T20:10:00.000Z,CCAFS SLC 40,B1015,SpaceX CRS-6,NaN,NaN,NASA (CRS),True,False
22,23,2015-04-27T23:03:00.000Z,CCAFS SLC 40,B1016,Turkmenistan / MonacoSAT,NaN,NaN,Turkmenistan National Space Agency,True,NaN
23,24,2015-06-28T14:21:00.000Z,CCAFS SLC 40,B1018,SpaceX CRS-7,NaN,NaN,NASA (CRS),False,NaN
24,25,2015-12-22T01:29:00.000Z,CCAFS SLC 40,B1019,Orbcomm-OG2-M2,NaN,NaN,Orbcomm,True,True
25,26,2016-01-17T15:42:00.000Z,VAFB SLC 4E,B1017,Jason-3,NaN,NaN,NASA,True,False
26,27,2016-03-04T23:35:00.000Z,CCAFS SLC 40,B1020,SES-9,NaN,NaN,SES,True,False
27,28,2016-04-08T20:43:00.000Z,CCAFS SLC 40,B1021,SpaceX CRS-8,NaN,NaN,NASA (CRS),True,True
28,29,2016-05-06T05:21:00.000Z,CCAFS SLC 40,B1022,JCSAT-2B,NaN,NaN,SKY Perfect JSAT Group,True,True
29,30,2016-05-27T21:39:00.000Z,CCAFS SLC 40,B1023,Thaicom 8,NaN,NaN,Thaicom,True,True
...,...,...,...,...,...,...,...,...,...,...
37,38,2017-03-30T22:27:00.000Z,KSC LC 39A,B1021,SES-10,NaN,NaN,SES,True,True
38,39,2017-05-01T11:15:00.000Z,KSC LC 39A,B1032,NROL-76,NaN,NaN,NRO,True,True
39,40,2017-05-15T23:21:00.000Z,KSC LC 39A,B1034,Inmarsat-5 F4,NaN,NaN,Inmarsat,True,NaN
40,41,2017-06-03T21:07:00.000Z,KSC LC 39A,B1035,SpaceX CRS-11,NaN,NaN,NASA (CRS),True,True
41,42,2017-06-23T19:10:00.000Z,KSC LC 39A,B1029,BulgariaSat-1,NaN,NaN,Bulgaria Sat,True,True
42,43,2017-06-25T13:25:00.000Z,VAFB SLC 4E,B1036,Iridium NEXT 2,NaN,NaN,Iridium Communications,True,True
43,44,2017-07-05T23:35:00.000Z,KSC LC 39A,B1037,Intelsat 35e,NaN,NaN,Intelsat,True,NaN
44,45,2017-08-14T16:31:00.000Z,KSC LC 39A,B1039,SpaceX CRS-12,NaN,NaN,NASA (CRS),True,True
45,46,2017-08-24T18:50:00.000Z,VAFB SLC 4E,B1038,FormoSat-5,NaN,NaN,NSPO (Taiwan),True,True
46,47,2017-09-07T13:50:00.000Z,KSC LC 39A,B1040,X-37B OTV-5,NaN,NaN,USAF,True,True
47,48,2017-10-09T12:37:00.000Z,VAFB SLC 4E,B1041,Iridium NEXT 3,NaN,NaN,Iridium Communications,True,True
48,49,2017-10-11T22:53:00.000Z,KSC LC 39A,B1031,SES-11 / Echostar 105,NaN,NaN,SES,True,True
49,50,2017-10-30T19:34:00.000Z,KSC LC 39A,B1042,KoreaSat 5A,NaN,NaN,KT Corporation,True,True
50,51,2017-12-15T15:36:00.000Z,CCAFS SLC 40,B1035,SpaceX CRS-13,NaN,NaN,NASA (CRS),True,True
51,52,2017-12-23T01:27:23.000Z,VAFB SLC 4E,B1036,Iridium NEXT 4,NaN,NaN,Iridium Communications,True,True
52,53,2018-01-08T01:00:00.000Z,CCAFS SLC 40,B1043,ZUMA,NaN,NaN,Northrop Grumman,True,True
53,54,2018-01-31T21:25:00.000Z,CCAFS SLC 40,B1032,GovSat-1,NaN,NaN,GovSat,True,True
54,55,2018-02-06T20:45:00.000Z,KSC LC 39A,B1033,Tesla Roadster,NaN,NaN,SpaceX,True,False
55,56,2018-02-22T14:17:00.000Z,VAFB SLC 4E,B1038,Paz,800.0,SSO,HisdeSAT,True,NaN
56,57,2018-03-06T05:33:00.000Z,CCAFS SLC 40,B1044,Hispasat 30W-6,NaN,NaN,Hispasat,True,NaN
57,58,2018-03-30T14:13:51.000Z,VAFB SLC 4E,B1041,Iridium NEXT 5,NaN,NaN,Iridium Communications,True,NaN
58,59,2018-04-02T20:30:41.000Z,CCAFS SLC 40,B1039,SpaceX CRS-14,NaN,NaN,NASA (CRS),True,NaN
59,60,2018-04-18T22:51:00.000Z,CCAFS SLC 40,B1045,TESS,NaN,NaN,NASA,True,True
60,61,2018-05-11T20:14:00.000Z,KSC LC 39A,B1046,Bangabandhu-1,NaN,NaN,Bangladesh Gov,True,True
61,62,2018-05-22T19:47:58.000Z,VAFB SLC 4E,B1043,Iridium NEXT 6,1160.0,PO,Iridium Communications,True,NaN
62,63,2018-06-04T04:45:00.000Z,CCAFS SLC 40,B1040,SES-12,NaN,NaN,SES,True,NaN
63,64,2018-06-29T09:42:00.000Z,CCAFS SLC 40,B1045,SpaceX CRS-15,NaN,NaN,NASA (CRS),True,NaN
64,65,2018-07-22T05:50:00.000Z,CCAFS SLC 40,B1047,Telstar 19V,NaN,NaN,Telesat,True,True
65,66,2018-07-25T11:39:26.000Z,VAFB SLC 4E,B1048,Iridium NEXT 7,NaN,NaN,Iridium Communications,True,True
66,67,2018-08-07T05:18:00.000Z,CCAFS SLC 40,B1046,Telkom-4,NaN,NaN,Telkom,True,True

In [49]:
data_min_1 = data_min_df_transformed.rename(columns={"flight_number": "flight_Number",
                                          "launch_date_utc": "launch_date",
                                          "rocket/first_stage/cores/0/core_serial": "booster_version",
                                          "launch_site/site_name": "launch_site",
                                          "rocket/second_stage/payloads/0/payload_id":"payload_name",
                                          "rocket/second_stage/payloads/1/payload_mass_kg":"payload_mass",
                                          "rocket/second_stage/payloads/1/orbit":"payload_orbit",
                                          "rocket/second_stage/payloads/0/customers/0":"customer_name",
                                          "launch_success":"mission_outcome",
                                          "rocket/first_stage/cores/0/land_success":"landing_outcome"})
data_min_1

,flight_Number,launch_date,launch_site,booster_version,payload_name,payload_mass,payload_orbit,customer_name,mission_outcome,landing_outcome
0,1,2006-03-24T22:30:00.000Z,Kwajalein Atoll,Merlin1A,FalconSAT-2,NaN,NaN,DARPA,False,False
1,2,2007-03-21T01:10:00.000Z,Kwajalein Atoll,Merlin2A,DemoSAT,NaN,NaN,DARPA,False,False
2,3,2008-08-02T03:34:00.000Z,Kwajalein Atoll,Merlin1C,Trailblazer,NaN,LEO,NASA,False,False
3,4,2008-09-28T23:15:00.000Z,Kwajalein Atoll,Merlin2C,RatSat,NaN,NaN,SpaceX,True,False
4,5,2009-07-13T03:35:00.000Z,Kwajalein Atoll,Merlin3C,RazakSAT,NaN,NaN,ATSB,True,False
5,6,2010-06-04T18:45:00.000Z,CCAFS SLC 40,B0003,Dragon Qualification Unit,NaN,NaN,SpaceX,True,False
6,7,2010-12-08T15:43:00.000Z,CCAFS SLC 40,B0004,COTS Demo Flight 1,NaN,LEO,NASA(COTS),True,False
7,8,2012-05-22T07:44:00.000Z,CCAFS SLC 40,B0005,COTS Demo Flight 2,NaN,NaN,NASA(COTS),True,NaN
8,9,2012-10-08T00:35:00.000Z,CCAFS SLC 40,B0006,SpaceX CRS-1,400.0,LEO,NASA (CRS),True,NaN
9,10,2013-03-01T19:10:00.000Z,CCAFS SLC 40,B0007,SpaceX CRS-2,NaN,NaN,NASA (CRS),True,NaN
10,11,2013-09-29T16:00:00.000Z,VAFB SLC 4E,B1003,CASSIOPE,NaN,NaN,MDA,True,False
11,12,2013-12-03T22:41:00.000Z,CCAFS SLC 40,B1004,SES-8,NaN,NaN,SES,True,NaN
12,13,2014-01-06T18:06:00.000Z,CCAFS SLC 40,B1005,Thaicom 6,NaN,NaN,Thaicom,True,NaN
13,14,2014-04-18T19:25:00.000Z,CCAFS SLC 40,B1006,SpaceX CRS-3,NaN,NaN,NASA (CRS),True,True
14,15,2014-07-14T15:15:00.000Z,CCAFS SLC 40,B1007,Orbcomm-OG2-M1,NaN,NaN,Orbcomm,True,True
15,16,2014-08-05T08:00:00.000Z,CCAFS SLC 40,B1008,AsiaSat 8,NaN,NaN,AsiaSat,True,NaN
16,17,2014-09-07T05:00:00.000Z,CCAFS SLC 40,B1011,AsiaSat 6,NaN,NaN,AsiaSat,True,NaN
17,18,2014-09-21T05:52:00.000Z,CCAFS SLC 40,B1010,SpaceX CRS-4,NaN,NaN,NASA (CRS),True,False
18,19,2015-01-10T09:47:00.000Z,CCAFS SLC 40,B1012,SpaceX CRS-5,NaN,NaN,NASA (CRS),True,False
19,20,2015-02-11T23:03:00.000Z,CCAFS SLC 40,B1013,DSCOVR,NaN,NaN,NASA,True,True
20,21,2015-03-02T03:50:00.000Z,CCAFS SLC 40,B1014,ABS-3A,2205.0,GTO,ABS,True,NaN
21,22,2015-04-14T20:10:00.000Z,CCAFS SLC 40,B1015,SpaceX CRS-6,NaN,NaN,NASA (CRS),True,False
22,23,2015-04-27T23:03:00.000Z,CCAFS SLC 40,B1016,Turkmenistan / MonacoSAT,NaN,NaN,Turkmenistan National Space Agency,True,NaN
23,24,2015-06-28T14:21:00.000Z,CCAFS SLC 40,B1018,SpaceX CRS-7,NaN,NaN,NASA (CRS),False,NaN
24,25,2015-12-22T01:29:00.000Z,CCAFS SLC 40,B1019,Orbcomm-OG2-M2,NaN,NaN,Orbcomm,True,True
25,26,2016-01-17T15:42:00.000Z,VAFB SLC 4E,B1017,Jason-3,NaN,NaN,NASA,True,False
26,27,2016-03-04T23:35:00.000Z,CCAFS SLC 40,B1020,SES-9,NaN,NaN,SES,True,False
27,28,2016-04-08T20:43:00.000Z,CCAFS SLC 40,B1021,SpaceX CRS-8,NaN,NaN,NASA (CRS),True,True
28,29,2016-05-06T05:21:00.000Z,CCAFS SLC 40,B1022,JCSAT-2B,NaN,NaN,SKY Perfect JSAT Group,True,True
29,30,2016-05-27T21:39:00.000Z,CCAFS SLC 40,B1023,Thaicom 8,NaN,NaN,Thaicom,True,True
...,...,...,...,...,...,...,...,...,...,...
37,38,2017-03-30T22:27:00.000Z,KSC LC 39A,B1021,SES-10,NaN,NaN,SES,True,True
38,39,2017-05-01T11:15:00.000Z,KSC LC 39A,B1032,NROL-76,NaN,NaN,NRO,True,True
39,40,2017-05-15T23:21:00.000Z,KSC LC 39A,B1034,Inmarsat-5 F4,NaN,NaN,Inmarsat,True,NaN
40,41,2017-06-03T21:07:00.000Z,KSC LC 39A,B1035,SpaceX CRS-11,NaN,NaN,NASA (CRS),True,True
41,42,2017-06-23T19:10:00.000Z,KSC LC 39A,B1029,BulgariaSat-1,NaN,NaN,Bulgaria Sat,True,True
42,43,2017-06-25T13:25:00.000Z,VAFB SLC 4E,B1036,Iridium NEXT 2,NaN,NaN,Iridium Communications,True,True
43,44,2017-07-05T23:35:00.000Z,KSC LC 39A,B1037,Intelsat 35e,NaN,NaN,Intelsat,True,NaN
44,45,2017-08-14T16:31:00.000Z,KSC LC 39A,B1039,SpaceX CRS-12,NaN,NaN,NASA (CRS),True,True
45,46,2017-08-24T18:50:00.000Z,VAFB SLC 4E,B1038,FormoSat-5,NaN,NaN,NSPO (Taiwan),True,True
46,47,2017-09-07T13:50:00.000Z,KSC LC 39A,B1040,X-37B OTV-5,NaN,NaN,USAF,True,True
47,48,2017-10-09T12:37:00.000Z,VAFB SLC 4E,B1041,Iridium NEXT 3,NaN,NaN,Iridium Communications,True,True
48,49,2017-10-11T22:53:00.000Z,KSC LC 39A,B1031,SES-11 / Echostar 105,NaN,NaN,SES,True,True
49,50,2017-10-30T19:34:00.000Z,KSC LC 39A,B1042,KoreaSat 5A,NaN,NaN,KT Corporation,True,True
50,51,2017-12-15T15:36:00.000Z,CCAFS SLC 40,B1035,SpaceX CRS-13,NaN,NaN,NASA (CRS),True,True
51,52,2017-12-23T01:27:23.000Z,VAFB SLC 4E,B1036,Iridium NEXT 4,NaN,NaN,Iridium Communications,True,True
52,53,2018-01-08T01:00:00.000Z,CCAFS SLC 40,B1043,ZUMA,NaN,NaN,Northrop Grumman,True,True
53,54,2018-01-31T21:25:00.000Z,CCAFS SLC 40,B1032,GovSat-1,NaN,NaN,GovSat,True,True
54,55,2018-02-06T20:45:00.000Z,KSC LC 39A,B1033,Tesla Roadster,NaN,NaN,SpaceX,True,False
55,56,2018-02-22T14:17:00.000Z,VAFB SLC 4E,B1038,Paz,800.0,SSO,HisdeSAT,True,NaN
56,57,2018-03-06T05:33:00.000Z,CCAFS SLC 40,B1044,Hispasat 30W-6,NaN,NaN,Hispasat,True,NaN
57,58,2018-03-30T14:13:51.000Z,VAFB SLC 4E,B1041,Iridium NEXT 5,NaN,NaN,Iridium Communications,True,NaN
58,59,2018-04-02T20:30:41.000Z,CCAFS SLC 40,B1039,SpaceX CRS-14,NaN,NaN,NASA (CRS),True,NaN
59,60,2018-04-18T22:51:00.000Z,CCAFS SLC 40,B1045,TESS,NaN,NaN,NASA,True,True
60,61,2018-05-11T20:14:00.000Z,KSC LC 39A,B1046,Bangabandhu-1,NaN,NaN,Bangladesh Gov,True,True
61,62,2018-05-22T19:47:58.000Z,VAFB SLC 4E,B1043,Iridium NEXT 6,1160.0,PO,Iridium Communications,True,NaN
62,63,2018-06-04T04:45:00.000Z,CCAFS SLC 40,B1040,SES-12,NaN,NaN,SES,True,NaN
63,64,2018-06-29T09:42:00.000Z,CCAFS SLC 40,B1045,SpaceX CRS-15,NaN,NaN,NASA (CRS),True,NaN
64,65,2018-07-22T05:50:00.000Z,CCAFS SLC 40,B1047,Telstar 19V,NaN,NaN,Telesat,True,True
65,66,2018-07-25T11:39:26.000Z,VAFB SLC 4E,B1048,Iridium NEXT 7,NaN,NaN,Iridium Communications,True,True
66,67,2018-08-07T05:18:00.000Z,CCAFS SLC 40,B1046,Telkom-4,NaN,NaN,Telkom,True,True

In [50]:
data_min_1.to_csv("data_min_revised.csv", encoding='utf-8', index=False)

In [53]:
connection_string = "root:lhs20035473@localhost/spacex_db"
engine = create_engine(f'mysql://{connection_string}')

In [54]:
data_min_1.to_sql(name='spacex_min', con=engine, if_exists='append', index=True)

In [67]:
spacex_1 = "databasespacex.csv"
spacex_launch_df = pd.read_csv(spacex_1)
spacex_launch_df.head()

,flight_number,launch_date,launch_time,launch_site,vehicle_type,payload_name,payload_type,payload_mass,payload_orbit,customer_name,customer_type,customer_country,mission_outcome,failure_reason,landing_type,landing_outcome
0,F1-1,24-Mar-06,22:30,Marshall Islands,Falcon 1,FalconSAT-2,Research Satellite,19.5,NaN,DARPA,Government,United States,Failure,Engine Fire During Launch,NaN,NaN
1,F1-2,21-Mar-07,1:10,Marshall Islands,Falcon 1,DemoSat,NaN,NaN,NaN,DARPA,Government,United States,Failure,Engine Shutdown During Launch,NaN,NaN
2,F1-3,3-Aug-08,3:34,Marshall Islands,Falcon 1,Trailblazer,Communication Satellite,NaN,NaN,ORS,Government,United States,Failure,Collision During Launch,NaN,NaN
3,F1-3,3-Aug-08,3:34,Marshall Islands,Falcon 1,"PRESat, NanoSail-D",Research Satellites,8.0,NaN,NASA,Government,United States,Failure,Collision During Launch,NaN,NaN
4,F1-3,3-Aug-08,3:34,Marshall Islands,Falcon 1,Explorers,Human Remains,NaN,NaN,Celestis,Business,United States,Failure,Collision During Launch,NaN,NaN

In [68]:
spacex_launch_df.to_sql(name='spacex_launch', con=engine, if_exists='append', index=True)

In [57]:
spacex_2006_df.to_sql(name='spacex_2006', con=engine, if_exists='append', index=True)

In [69]:
spacex_2 = "Updated_spacex_2006_to_present.csv"
spacex_2006_df = pd.read_csv(spacex_2)
spacex_2006_df.head(20)

,Unnamed: 0,flight_number,launch_date,launch_time,launch_site,payload_name,payload_mass,payload_orbit,customer_name,mission_outcome,landing_outcome
0,0,F1-1,24-Mar-06,22:30,Marshall Islands,FalconSAT-2,19.5,NaN,DARPA,Failure,NaN
1,1,F1-2,21-Mar-07,1:10,Marshall Islands,DemoSat,NaN,NaN,DARPA,Failure,NaN
2,2,F1-3,3-Aug-08,3:34,Marshall Islands,Trailblazer,NaN,NaN,ORS,Failure,NaN
3,3,F1-3,3-Aug-08,3:34,Marshall Islands,"PRESat, NanoSail-D",8.0,NaN,NASA,Failure,NaN
4,4,F1-3,3-Aug-08,3:34,Marshall Islands,Explorers,NaN,NaN,Celestis,Failure,NaN
5,5,F1-4,28-Sep-08,23:15,Marshall Islands,RatSat (DemoSat),165.0,Low Earth Orbit,NaN,Success,NaN
6,6,F1-5,14-Jul-09,3:35,Marshall Islands,RazakSAT,180.0,Low Earth Orbit,ATSB,Success,NaN
7,7,F9-1,4-Jun-10,18:45,Cape Canaveral AFS LC-40,Dragon Spacecraft Qualification Unit,NaN,Low Earth Orbit,NaN,Success,Failure
8,8,F9-2,8-Dec-10,15:43,Cape Canaveral AFS LC-40,SpaceX CRS (Dragon C1),NaN,Low Earth Orbit,NASA,Success,Failure
9,9,F9-3,22-May-12,7:44,Cape Canaveral AFS LC-40,SpaceX CRS (Dragon C2+),NaN,Low Earth Orbit,NASA,Success,NaN
10,10,F9-4,8-Oct-12,0:35,Cape Canaveral AFS LC-40,SpaceX CRS-1,500.0,Low Earth Orbit,NASA,Success,NaN
11,11,F9-4,8-Oct-12,0:35,Cape Canaveral AFS LC-40,Orbcomm-OG2,150.0,Low Earth Orbit,Orbcomm,Failure,NaN
12,12,F9-5,1-Mar-13,15:10,Cape Canaveral AFS LC-40,SpaceX CRS-2,677.0,Low Earth Orbit,NASA,Success,NaN
13,13,F9-6,29-Sep-13,16:00,Vandenberg AFB SLC-4E,CASSIOPE,500.0,Polar Orbit,MDA Corp,Success,Failure
14,14,F9-7,3-Dec-13,22:41,Cape Canaveral AFS LC-40,SES-8,3170.0,Geostationary Transfer Orbit,SES,Success,NaN
15,15,F9-8,6-Dec-14,22:06,Cape Canaveral AFS LC-40,Thaicom 6,3325.0,Geostationary Transfer Orbit,Thaicom,Success,NaN
16,16,F9-9,18-Apr-14,19:25,Cape Canaveral AFS LC-40,SpaceX CRS-3,2296.0,Low Earth Orbit,NASA,Success,Success
17,17,F9-10,14-Jul-14,15:15,Cape Canaveral AFS LC-40,OG2 Mission 1 (6 OG2 Satellites),NaN,Low Earth Orbit,Orbcomm,Success,Success
18,18,F9-11,5-Aug-14,8:00,Cape Canaveral AFS LC-40,AsiaSat 8,4535.0,Geostationary Transfer Orbit,AsiaSat,Success,NaN
19,19,F9-12,7-Sep-14,5:00,Cape Canaveral AFS LC-40,AsiaSat 6,4428.0,Geostationary Transfer Orbit,AsiaSat,Success,NaN

In [70]:
spacex_2006_df.to_sql(name='spacex_2006', con=engine, if_exists='append', index=True)